import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Test.module.scss'
import AnimationWrapper from '@/components/AnimationWrapper'

const Test: NextPage = () => {
return (
    <AnimationWrapper>
        <div id='test'>
        <Head>
            <title>Test page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>    
        <h1>Sample Text</h1>
        {/* <Image src="/astronaut.png" alt="Astronaut" width={500} height={500} /> */}
        <div className={styles.glassTest}>
            <h1>😉</h1>
        </div>
        </div>
    </AnimationWrapper>
)
}

export default Test
