import type { NextPage } from 'next'
import Head from 'next/head'

const Test: NextPage = () => {
return (
    <div id='test'>
    <Head>
        <title>Test page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>    
    <h1>Sample Text</h1>
    </div>
)
}

export default Test
